<?php
declare(strict_types=1);
?>
<?=$this->header?>
<main id="app-main" class="container">
    <div class="row center-xs">
        <div class="col-xs-10">
            <div class="box">
                <article>
                    <p>Access Denied. You do not have the required access level to access this resource.</p>
                </article>
            </div>
        </div>
    </div>
</main>
<?=$this->footer?>