<?php
declare(strict_types=1);
?>
<?=$this->header?>
<main id="app-main" class="container">
    <div class="row center-xs">
        <div class="col-xs-6">
            <div class="box">
                <article>
                <?php
                    if (isset($this->form)) {
                        echo $this->form($this->form);
                    }
                ?>
                </article>
            </div>
        </div>
    </div>
</main>
<?=$this->footer?>