<?php

declare(strict_types=1);

$this->headTitle(ucfirst($this->currentRoute));
?>
<?=$this->header?>
<main id="app-main" class="container">
    <div class="row center-xs">
        <div class="col-xs-6">
            <div class="box">
                <article>
                <?php
                    if (isset($this->form)) {
                        $this->form->setAttribute('action', $this->url('user-manager.login'));
                        echo $this->form($this->form);
                    }
                ?>
            <span>Forgot your password?
                    <a href="<?=$this->url('user-manager.reset');?>">Reset Password</a>
                </span>
                </article>
            </div>
        </div>
    </div>
</main>
<?=$this->footer?>
