<?php

declare(strict_types=1);

use Tracy\Debugger;

$this->headTitle('Register');

?>
<div class="row center-xs">
    <div class="col-xs-6">
        <div class="box">
            <article>
            <?php
                if (isset($this->form)) {
                    $this->form->setAttribute('action', $this->url('user-manager.register'));
                    echo $this->form($this->form);
                }
            ?>
            </article>
            <?php
            Debugger::barDump($this->form->getMessages());
            ?>
        </div>
    </div>
</div>


