<?php
declare(strict_types=1);
?>
<?=$this->header?>
<main id="app-main" class="container">
    <?php
    if (isset($this->form)) {
    ?>
    <div class="row center-xs">
        <div class="col-xs-6">
            <div class="box">
                <article>
                <?php
                    echo $this->form($this->form);
                ?>
                </article>
            </div>
        </div>
    </div>
    <?php
    }
    ?>
</main>
<?=$this->footer?>