<?php

declare(strict_types=1);

$this->headTitle('Verify Account');
?>
<div class="row center-xs">
    <div class="col-xs-6">
        <div class="box">
            <article>
            <?php
                if (isset($this->form)) {
                    //$this->form->setAttribute('action', $this->url('user-manager.register'));
                    echo $this->form($this->form);
                }
            ?>
            </article>
        </div>
    </div>
</div>

