<?php

declare(strict_types=1);

$this->headMeta()
    ->setCharSet('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1')
    ->appendName('color-scheme', 'light dark')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

$this->headLink(
    [
        'rel'  => 'shortcut icon',
        'href' => 'https://getlaminas.org/images/favicon/favicon.ico',
    ]
);
// styles
$this->headLink()
    ->appendStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.green.min.css')
    ->appendStylesheet($this->basePath('front-end/css/pico-override.css'))
    ->appendStylesheet($this->basePath('front-end/css/style.css'));
// head script files and script

$this->headScript()
->appendFile(
    'https://unpkg.com/htmx.org@2.0.1/dist/htmx.js',
    'text/javascript',
    [
        'integrity' => 'sha384-gpIh5aLQ0qmX8kZdyhsd6jA24uKLkqIr1WAGtantR4KsS97l/NRBvh8/8OYGThAf',
        'crossorigin' => 'anonymous',
    ],
)->appendScript(
    "htmx.config = '$this->htmxConfig'",
    '',
    ['noescape' => true]
);

// inline script which is printed at bottom of page
// $this->inlineScript()
//     ->appendFile('https://code.jquery.com/jquery-3.5.1.min.js');
// ?>
<?=$this->doctype();?>

<html>
<head>
    <base href="<?=$this->basePath('/');?>" />
    <?=$this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
</head>
    <body>
        <header id="app-header" class="container" style="margin-top:0; padding-top: 0;">
            <nav style="margin-top:0; padding-top:0;">
                <!-- Brand -->
                <ul>
                    <li>
                        <a href="<?=$this->url('Home')?>">
                            <img src="https://docs.laminas.dev/img/laminas-mezzio-rgb.svg" alt="Laminas Mezzio" width="300" />
                        </a>
                    </li>
                </ul>
                <!-- Links -->
                <ul>
                    <li>
                        <a href="https://docs.mezzio.dev/mezzio" target="_blank">
                            <i class="fa fa-book"></i> Docs
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/mezzio/mezzio" target="_blank">
                            <i class="fa fa-wrench"></i> Contribute
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('api.ping')?>">
                            Ping Test
                        </a>
                    </li>
                    <?php
                    if ($this->user->getDetail('role_id') === 'Administrator'):
                    ?>
                    <li>
                        <a href="<?=$this->url('admin')?>">
                            Admin
                        </a>
                    </li>
                    <?php
                    endif;
                    ?>
                    <?php
                    if ($this->user->getIdentity() === 'guest'):
                    ?>
                    <li>
                        <a href="<?=$this->url('Login')?>">
                            Sign In
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('Register')?>">
                            Register
                        </a>
                    </li>
                    <?php
                    else:
                    ?>
                    <li>
                        <a href="<?=$this->url('user-manager.account')?>">
                            Account
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('Logout')?>">
                            Sign Out
                        </a>
                    </li>
                    <?php
                    endif;
                    ?>
                </ul>
            </nav>
        </header>
        <main id="app-main" class="container">
            <?=$this->content?>
        </main>
        <footer id="app-footer" class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
            </p>
        </footer>
        <?=$this->inlineScript()?>
    </body>
</html>
