<?php

declare(strict_types=1);

$this->headMeta()
    ->setCharSet('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1')
    ->appendName('color-scheme', 'light dark')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

$this->headLink(
    [
        'rel'  => 'shortcut icon',
        'href' => $this->basePath('front-end/images/mm16.png'),
    ]
);

// styles
$this->headLink()
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css')
    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css')
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.jade.min.css')
    ->appendStylesheet($this->basePath('front-end/css/pico-override.css'))
    ->appendStylesheet($this->basePath('front-end/css/style.css'));

// head script files and script
$this->headScript()
->appendFile(
    'https://unpkg.com/htmx.org@2.0.1/dist/htmx.js',
    'text/javascript',
    [
        'integrity' => 'sha384-gpIh5aLQ0qmX8kZdyhsd6jA24uKLkqIr1WAGtantR4KsS97l/NRBvh8/8OYGThAf',
        'crossorigin' => 'anonymous',
    ],
);
// $this->headScript()->appendScript(
//     "htmx.config = '$this->htmxConfig'",
//     '',
//     ['noescape' => true]
// );

// inline script which is printed at bottom of page
$this->inlineScript()
    ->appendFile($this->basePath('front-end/js/app.js'));
?>
<?=$this->doctype();?>

<html>
    <head>
        <base href="<?=$this->basePath('/');?>" />
        <?=$this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?>
        <?=$this->headMeta()?>
        <?=$this->headLink()?>
        <?=$this->headScript()?>
    </head>
    <body>
        <header id="app-header" class="container" style="margin-top:0; padding-top: 0;">
            <nav id="nav">
                <!-- Brand -->
                <ul>
                    <li>
                        <a href="<?=$this->url('home')?>">
                            <img src="<?=$this->basePath('front-end/images/mm7.png')?>" alt="Mastering Mezzio" width="300" />
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="https://github.com/tyrsson/masteringmezzio.com" target="_blank">
                            <i class="bi-github"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/tyrsson/masteringmezzio.com/discussions" target="_blank">
                            <i class="bi-envelope-fill"></i>
                        </a>
                    </li>
                </ul>
                <!-- Links -->
                <ul>
                    <?php
                    if ($this->authz($this->request)->isGranted('admin.dashboard.read')):
                    ?>
                    <li>
                        <a href="<?=$this->url('admin.dashboard')?>">
                            Admin
                        </a>
                    </li>
                    <?php
                    endif;
                    ?>
                    <?php
                    //if ($this->user->getIdentity() === 'guest'):
                    if ($this->authz($this->request)->isGranted('user-manager.login')):
                    ?>
                    <li>
                        <a href="<?=$this->url('user-manager.login')?>">
                            Sign In
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('user-manager.register')?>">
                            Register
                        </a>
                    </li>
                    <?php
                    else:
                    ?>
                    <li>
                        <a href="<?=$this->url('user-manager.account')?>">
                            Account
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('user-manager.logout')?>">
                            Sign Out
                        </a>
                    </li>
                    <?php
                    endif;
                    ?>
                </ul>
            </nav>
        </header>
        <main id="app-main" class="container">
            <?=$this->content?>
        </main>
        <footer id="app-footer" class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> <a href="https://masteringmezzio.com/">Mastering Mezzio</a> All Rights Reserved.
            </p>
        </footer>
        <?=$this->inlineScript()?>
    </body>
</html>
