<?php

declare(strict_types=1);

$this->headTitle('Admin Dashboard');

?>
<?=$this->header?>
<main id="app-main" class="container">
    <div class="row center-xs">
        <div class="col-xs-10">
            <div class="box">
                <article>
                    <p>Template for App\Handler\DashboardHandler</p>
                </article>
            </div>
        </div>
    </div>
</main>
<?=$this->footer?>