<?php $this->headTitle('Home'); ?>

<?=$this->header?>
<main id="app-main" class="container">
    <article>
        <div>
            <h2 class="pico-color-jade-500">Welcome to Mastering Mezzio</h2>
            <p>
                Your best source for update to date "far beyond the docs" guides, tutorials and tips & tricks to
                get you up and running with Mezzio Micro Framework.
            </p>
            <p>
                You can feel confident that you are never wasting your time sharpening your skills with our guides
                because you are using the code they are built around right now. Yep, that's right all of our guides have
                been developed while building many different web applications but mainly the one that is powering this site.
            </p>
        </div>
    </article>
</main>
<?=$this->footer?>




