<?php
declare(strict_types=1);
?>
<article>
    <div>
        <h2 class="pico-color-jade-500">Welcome to Mastering Mezzio</h2>
        <p>
            Your best source for up to date "far beyond the docs" guides, tutorials and tips & tricks to
            get you up and running with Mezzio Micro Framework.
        </p>
        <p>
            You can feel confident that you are never wasting your time sharpening your skills with our guides
            because you are using the code they are built around right now.
        </p>
    </div>
</article>





