<?php
declare(strict_types=1);

use Axleus\Message\SystemMessage;

$this->headTitle($this->appName)->setSeparator(' - ')->setAutoEscape(false)
?>
<?=$this->headTitle($this->title);?>
<header id="app-header" class="container" style="margin-top:0; padding-top: 0;">
    <nav id="nav">
        <!-- Brand -->
        <ul>
            <li>
                <a href="<?=$this->url('Home')?>">
                    <img src="<?=$this->basePath('front-end/images/mm7.png')?>" alt="Mastering Mezzio" width="300" />
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="https://github.com/tyrsson/masteringmezzio.com" target="_blank">
                    <i class="bi-github"></i>
                </a>
            </li>
            <li>
                <a href="https://github.com/tyrsson/masteringmezzio.com/discussions" target="_blank">
                    <i class="bi-envelope-fill"></i>
                </a>
            </li>
        </ul>
        <!-- Links -->
        <ul>
            <?php
            if ($this->authz($this->request)->isGranted('Admin Dashboard.read')):
            ?>
            <li>
                <a href="<?=$this->url('Admin Dashboard')?>">
                    Admin
                </a>
            </li>
            <?php
            endif;
            ?>
            <?php
            if ($this->authz($this->request)->isGranted('Login')):
            ?>
            <li>
                <a href="<?=$this->url('Login')?>">
                    Sign In
                </a>
            </li>
            <li>
                <a href="<?=$this->url('Register')?>">
                    Register
                </a>
            </li>
            <?php
            else:
            ?>
            <li>
                <a href="<?=$this->url('Account')?>">
                    Account
                </a>
            </li>
            <li>
                <a href="<?=$this->url('Logout')?>">
                    Sign Out
                </a>
            </li>
            <?php
            endif;
            ?>
        </ul>
    </nav>
    <?=$this->systemMessage(SystemMessage::SYSTEM_MESSAGE_KEY)?>
</header>