<?php

declare(strict_types=1);

use Axleus\Message\SystemMessage;

$this->headMeta()
    ->setCharSet('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1')
    ->appendName('color-scheme', 'light dark')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

$this->headLink(
    [
        'rel'  => 'shortcut icon',
        'href' => $this->basePath('front-end/images/mm16.png'),
    ]
);

// styles
$this->headLink()
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css')
    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css')
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.jade.min.css')
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.colors.min.css')
    ->appendStylesheet($this->basePath('front-end/css/pico-override.css'))
    ->appendStylesheet($this->basePath('front-end/css/style.css'));

// head script files and script
$this->headScript()
->appendFile(
    'https://unpkg.com/htmx.org@2.0.1/dist/htmx.js',
    'text/javascript',
    [
        'integrity' => 'sha384-gpIh5aLQ0qmX8kZdyhsd6jA24uKLkqIr1WAGtantR4KsS97l/NRBvh8/8OYGThAf',
        'crossorigin' => 'anonymous',
    ],
);

$this->headScript()
->appendScript(
    'let dismissMessage = null',
    'text/javascript',
);

// $this->headScript()->appendScript(
//     "htmx.config = '$this->htmxConfig'",
//     '',
//     ['noescape' => true]
// );
if ($this->config['debug']) {
    $this->headScript()
        ->appendFile(
        $this->basePath('front-end/js/debug.js'),
        'text/javascript',
    );
}

// inline script which is printed at bottom of page
$this->inlineScript()
    ->appendFile($this->basePath('front-end/js/app.js'));
?>
<?=$this->doctype();?>
<html>
    <head>
        <base href="<?=$this->basePath('/');?>" />
        <?=$this->headMeta()?>
        <?=$this->headLink()?>
        <?=$this->headScript()?>
    </head>
    <body hx-boost="true" hx-push-url="true">
        <?=$this->content?>
        <?=$this->inlineScript()?>
    </body>
</html>
